alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: API_KEY
  scope: RUN_AND_BUILD_TIME
  value: hsUHrPjjKYDZPDP9MLLgzCimGsxkMURUu
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: yt-scraper-proxy
    match:
      path:
        prefix: /
name: yt-scraper-ny
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: giltotherescue/yt-scraper-proxy
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: yt-scraper-proxy
  run_command: gunicorn --worker-tmp-dir /dev/shm app:app
  source_dir: /
