name: youtube-scraper
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: giltotherescue/yt-scraper-proxy
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  build_command: pip install -r requirements.txt
  run_command: gunicorn --worker-tmp-dir /dev/shm app:app
  envs:
  - key: API_KEY
    scope: RUN_TIME
    type: SECRET
    value: ${API_KEY} 