alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: API_KEY
  scope: RUN_AND_BUILD_TIME
  value: hsUHrPjjKYDZPDP9MLLgzCimGsxkMURUu
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: yt-scraper-proxy
    match:
      path:
        prefix: /
name: yt-scraper-ny
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: giltotherescue/yt-scraper-proxy
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: yt-scraper-proxy
  build_command: |
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | tee /etc/apt/trusted.gpg.d/google.asc
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google.list
    apt-get update
    apt-get install -y google-chrome-stable chromium-chromedriver
    pip install -r requirements.txt
  run_command: gunicorn --worker-tmp-dir /dev/shm app:app
  source_dir: /
