services:
  scraper:
    build:
      context: .
      no_cache: true
      # platform: linux/amd64
    container_name: yt-scraper-proxy-container
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
