steps:
  # Step 1: Deploy the image to Google Cloud Run Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '${_SUB_NAME_PREFIX}-${_INSTANCE_NAME_NUM}',
      '--image', '${_REPO_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_SUB_NAME_PREFIX}-image:latest',
      '--region', '${_REGION}',
      '--allow-unauthenticated',
      '--min-instances', '0',
      '--max-instances', '1',
      '--port', '${_PORT}',
      '--cpu', '2000m',
      '--memory', '2Gi',
      '--set-env-vars', 'PROJECT_ID=${_PROJECT_ID},API_KEY=${_API_KEY}',
      '--network', 'default',
      '--subnet', 'default',
    ]

substitutions:
  _PROJECT_ID: ''
  _PORT: ''
  _SUB_NAME_PREFIX: ''
  _ARTIFACT_REPO: ''
  _REGION: ''
  _REPO_REGION: ''
  _API_KEY: ''
  _INSTANCE_NAME_NUM: ''
timeout: '1600s'
